theme = "catppuccin_frappe"


[editor]
bufferline = "multiple"
line-number = "relative"
color-modes = true
auto-completion = true
auto-format = true
completion-trigger-len = 1
completion-replace = true
auto-info = true
true-color = true
undercurl = true

[editor.statusline]

left = ["mode", "spinner","version-control"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "||"

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = "⏎"  # set wrap-indicator to "" to hide it


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.insert]
j = { k = "normal_mode"}
